name = "AdaSubGram"
uuid = "39de99ea-98e8-4abf-a19e-a1c61e6261d6"
authors = ["Atour Mousavi Gourabi"]
version = "1.0.0-DEV"

[deps]
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
Unicode = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
