name = "AdaSubGram"
uuid = "39de99ea-98e8-4abf-a19e-a1c61e6261d6"
version = "0.1.0"
authors = ["Atour Mousavi Gourabi <amousavigourabi@gmail.com>"]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
DataStructures = "0.18.22, 0.19"
Dates = "1.11.0"
LinearAlgebra = "1.11.0"
MKL = "0.9.0"
Random = "1.11.0"
SpecialFunctions = "2.5.1"
Unicode = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
