name = "AdaSubGram"
uuid = "39de99ea-98e8-4abf-a19e-a1c61e6261d6"
authors = ["Atour Mousavi Gourabi"]
version = "1.0.0-DEV"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
DataStructures = "0.18.22"
Random = "1.11.0"
SpecialFunctions = "2.5.1"
Unicode = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
